workflow:
  metadata:
    id: 'load-area'
    name: 'Load Adventure Area'
    description: 'Load area file, describe scene, and present available options'
    version: '1.0.0'
    author: 'DM Assistant'

  installed_path: '{project-root}/src/modules/dm-assistant/workflows/load-area'
  instructions: '{installed_path}/README.md'
  validation: '{installed_path}/README.md'

  output:
    default_output_folder: '{project-root}/sessions/{session_name}/areas/'
    default_output_files:
      - 'current-area-status.md'
      - 'session-log-entry.md'

  integration:
    compatible_agents:
      - session-runner
      - campaign-manager
    compatible_workflows:
      - create-area
      - update-area
      - import-adventure

  steps:
    - step: 'select-area'
      title: 'Select Area File'
      description: 'Choose which area file to load'
      
    - step: 'describe-area'
      title: 'Present Area Description'
      description: 'Read area file and describe the scene to players'
      
    - step: 'show-options'
      title: 'Present Available Options'
      description: 'Display connections, encounters, and interactive elements'
      
    - step: 'await-action'
      title: 'Wait for DM Action'
      description: 'Listen for DM commands (move, search, combat, etc.)'

  web_bundle:
    name: 'load-area'
    description: 'Workflow for loading and presenting adventure areas.'
    author: 'DM Assistant'
    instructions: 'README.md'
    validation: 'README.md'
    template: 'area-loader.md'
    web_bundle_files:
      - 'area-loader.md'
      - 'README.md'

  completion:
    message: 'Area loaded. Awaiting DM instructions for player actions.'
    next_steps:
      - 'Use area connections to move to adjacent areas'
      - 'Start encounters using "start-combat" command'
      - 'Handle skill checks and exploration'