workflow:
  metadata:
    id: 'start-combat'
    name: 'Initialize Combat'
    description: 'Set up combat tracking from current area encounter'
    version: '1.0.0'
    author: 'DM Assistant'

  installed_path: '{project-root}/src/modules/dm-assistant/workflows/start-combat'
  instructions: '{installed_path}/README.md'
  validation: '{installed_path}/README.md'

  output:
    default_output_folder: '{project-root}/sessions/{session_name}/encounters/'
    default_output_files:
      - 'combat-status.md'
   
  integration:
    compatible_agents:
      - session-runner
      - campaign-manager
    compatible_workflows:
      - create-area
      - update-area
      - import-adventure

  steps:
    - step: 'identify-encounter'
      title: 'Load Encounter File'
      description: 'Identify which encounter to initiate from current area'
      
    - step: 'create-combat-files'
      title: 'Generate Combat Files'
      description: 'Create combat-status.md'
      
    - step: 'setup-tracking'
      title: 'Initialize Combat Tracking'
      description: 'Set up turn order and Round 0 status'
      
    
  web_bundle:
    name: 'start-combat'
    description: 'Workflow for initializing and tracking combat.'
    author: 'DM Assistant'
    instructions: 'README.md'
    validation: 'README.md'
    template: 'combat-initialization.md'
    web_bundle_files:
      - 'combat-initialization.md'
      - 'README.md'

  completion:
    message: 'Combat initialized. Ready for Round 1 actions.'
    next_steps:
      - 'Update combat log after each action'
      - 'Complete combat when DM declares end'