workflow:
  metadata:
    id: 'update-area'
    name: 'Update Area File'
    description: 'Edit, fix, or enhance an existing area file using shared templates.'
    version: '1.0.0'
    author: 'DM Assistant'
    tags:
      - area
      - update
      - workflow

  installed_path: '{project-root}/src/modules/dm-assistant/workflows/update-area'
  instructions: '{installed_path}/README.md'
  validation: '{installed_path}/README.md'
  documentation:
    overview: '{installed_path}/README.md'
    templates:
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/area-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/combat-encounter-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/trap-encounter-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/social-encounter-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/generic-encounter-template.md'
    guides:
      - '{project-root}/src/modules/dm-assistant/workflows/import-adventure/slyflourish-benchmark-guide.md'

  output:
    default_output_folder: '{project-root}/sessions/{session_name}/areas/'
    default_output_file: 'area-{area_number}-{sanitized_area_name}.md'
    format: 'markdown'
    validation: true

  integration:
    compatible_agents:
      - session-prep
      - dungeon-generator
      - campaign-manager
    compatible_workflows:
      - create-area
      - import-adventure

  steps:
    - step: 'select-area'
      title: 'Select Area File'
      description: 'Choose the area file to update.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/area-template.md'
    - step: 'edit-description'
      title: 'Edit Description & Features'
      description: 'Update area description, features, and connections.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/area-template.md'
    - step: 'update-encounters'
      title: 'Update Encounters'
      description: 'Add, remove, or modify encounters using shared templates.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/combat-encounter-template.md'
    - step: 'update-traps'
      title: 'Update Traps'
      description: 'Add or modify traps using shared template.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/trap-encounter-template.md'
    - step: 'update-social'
      title: 'Update Social Encounters'
      description: 'Add or modify social encounters using shared template.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/social-encounter-template.md'
    - step: 'update-generic'
      title: 'Update Generic Encounters'
      description: 'Add or modify generic encounters using shared template.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/generic-encounter-template.md'
    - step: 'validate-links'
      title: 'Validate Links & Ratings'
      description: 'Check all links and difficulty ratings for accuracy.'
      template: '{project-root}/src/modules/dm-assistant/workflows/create-area/area-template.md'

  web_bundle:
    name: 'update-area'
    description: 'Workflow for updating and enhancing area files.'
    author: 'DM Assistant'
    instructions: 'README.md'
    validation: 'README.md'
    template: '{project-root}/src/modules/dm-assistant/workflows/create-area/area-template.md'
    files:
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/area-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/combat-encounter-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/trap-encounter-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/social-encounter-template.md'
      - '{project-root}/src/modules/dm-assistant/workflows/create-area/generic-encounter-template.md'
      - 'README.md'
      - '{project-root}/src/modules/dm-assistant/workflows/import-adventure/slyflourish-benchmark-guide.md'

  completion:
    message: 'Area file updated. All changes validated and templates applied.'
    next_steps:
      - 'Review updated area for campaign fit'
      - 'Test encounter links and difficulty ratings'
      - 'Use session-runner to playtest changes'
